version: '3.8'

services:
  app:
    build: .
    env_file: ".env"
    depends_on:
      - db
    networks:
      - my_financial_net

  # superset:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.superset
  #   env_file: ".env"
  #   depends_on:
  #     - db
  #   volumes:
  #     - superset_home:/app/superset_home
  #   command: ["/app/docker-bootstrap.sh"]
  #   networks:
  #     - my_financial_net

  db:
    image: postgres:15
    container_name: my_financial_postgres
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my_financial_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - db
    networks:
      - my_financial_net

volumes:
  postgres_data:
  superset_home:

networks:
  my_financial_net:
    driver: bridge