version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_financial_postgres
    environment:
      POSTGRES_DB: my_financial_db
      POSTGRES_USER: my_financial_user
      POSTGRES_PASSWORD: my_financial_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 