FROM apache/superset:3.0.1

USER root
RUN pip install psycopg2-binary

COPY --chown=superset ./my_financial/superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

COPY docker-bootstrap.sh /app/docker-bootstrap.sh
RUN chmod +x /app/docker-bootstrap.sh

EXPOSE 8088