# Generated by Django 5.2.4 on 2025-07-28 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_country', models.CharField(choices=[('Brazil', 'Brazil'), ('Portugal', 'Portugal')], max_length=20)),
                ('currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('fx_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Foreign exchange fee percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('iof_percent', models.DecimalField(decimal_places=2, default=0, help_text='IOF (Imposto sobre Operações Financeiras) percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cardholder_name', models.CharField(max_length=100)),
                ('final_digits', models.CharField(help_text='Last 4 digits of the card', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
            },
        ),
        migrations.CreateModel(
            name='FixedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Brazil', 'Brazil'), ('Portugal', 'Portugal')], max_length=20)),
                ('description', models.CharField(help_text='Payment description', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('start_date', models.DateField(help_text='Start date of the payment')),
                ('end_date', models.DateField(blank=True, help_text='End date (optional, leave blank for ongoing payments)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fixed Payment',
                'verbose_name_plural': 'Fixed Payments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="User's full name", max_length=100)),
                ('base_currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro')], default='EUR', help_text='Base currency for calculations', max_length=3)),
                ('monthly_income_brl', models.DecimalField(decimal_places=2, default=0, help_text='Monthly income in Brazilian Real', max_digits=12)),
                ('monthly_income_eur', models.DecimalField(decimal_places=2, default=0, help_text='Monthly income in Euro', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Financial Profile',
                'verbose_name_plural': 'User Financial Profiles',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('to_currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate from_currency to to_currency', max_digits=10)),
                ('date', models.DateField(help_text='Date of the exchange rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VariablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the payment')),
                ('country', models.CharField(choices=[('Brazil', 'Brazil'), ('Portugal', 'Portugal')], max_length=20)),
                ('description', models.CharField(help_text='Payment description', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('health', 'Health'), ('education', 'Education'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=20)),
                ('linked_credit_card', models.BooleanField(default=False, help_text='Whether this payment was made with a credit card')),
                ('fx_fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Foreign exchange fee amount', max_digits=12)),
                ('iof_amount', models.DecimalField(decimal_places=2, default=0, help_text='IOF amount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(blank=True, help_text='Credit card used for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.creditcard')),
            ],
            options={
                'verbose_name': 'Variable Payment',
                'verbose_name_plural': 'Variable Payments',
                'ordering': ['-date'],
            },
        ),
    ]
