# Generated by Django 5.2.4 on 2025-07-28 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fixedpayment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userfinancialprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variablepayment',
            options={},
        ),
        migrations.AddField(
            model_name='userfinancialprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='final_digits',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='fx_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='iof_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixedpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fixedpayment',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fixedpayment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixedpayment',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='fixedpayment',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userfinancialprofile',
            name='base_currency',
            field=models.CharField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='userfinancialprofile',
            name='monthly_income_brl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userfinancialprofile',
            name='monthly_income_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userfinancialprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='variablepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variablepayment',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('education', 'Education'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='variablepayment',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.creditcard'),
        ),
        migrations.AlterField(
            model_name='variablepayment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='variablepayment',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='variablepayment',
            name='fx_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variablepayment',
            name='iof_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='variablepayment',
            name='linked_credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('fixed', 'Fixed Payment'), ('variable', 'Variable Payment')], max_length=10)),
                ('month_year', models.DateField(help_text='Month and year this payment is due (e.g., 2024-01-01 for January 2024)')),
                ('due_date', models.DateField(help_text='Specific due date for this payment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Checkbox to mark as paid')),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('BRL', 'Brazilian Real'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixed_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.fixedpayment')),
                ('variable_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.variablepayment')),
            ],
            options={
                'ordering': ['due_date', 'payment_type'],
                'unique_together': {('fixed_payment', 'month_year'), ('variable_payment', 'month_year')},
            },
        ),
    ]
