# Generated by Django 5.2.4 on 2025-07-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_creditcard_options_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this payment', null=True),
        ),
    ]
