# Generated by Django 5.2.4 on 2025-07-29 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_paymentstatus_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='payment_type',
            field=models.CharField(choices=[('fixed', 'Fixed Payment'), ('variable', 'Variable Payment'), ('credit_card', 'Credit Card Payment')], max_length=15),
        ),
        migrations.CreateModel(
            name='CreditCardInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the billing period')),
                ('end_date', models.DateField(help_text='End date of the billing period')),
                ('is_closed', models.BooleanField(default=False, help_text='Whether this invoice is closed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.creditcard')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
                'unique_together': {('credit_card', 'start_date', 'end_date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='paymentstatus',
            unique_together={('fixed_payment', 'month_year'), ('variable_payment', 'month_year')},
        ),
        migrations.AddField(
            model_name='paymentstatus',
            name='credit_card_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_statuses', to='finance.creditcardinvoice'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentstatus',
            unique_together={('credit_card_invoice', 'month_year'), ('fixed_payment', 'month_year'), ('variable_payment', 'month_year')},
        ),
    ]
