# Generated by Django 5.2.4 on 2025-07-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_paymentstatus_payment_type_creditcardinvoice_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='creditcardinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_closed', False)), fields=('credit_card',), name='unique_open_invoice_per_credit_card'),
        ),
    ]
