# Generated by Django 5.2.4 on 2025-07-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_creditcardinvoice_unique_open_invoice_per_credit_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcardinvoice',
            options={'ordering': ['-end_date', '-start_date'], 'verbose_name': 'Credit Card Invoice', 'verbose_name_plural': 'Credit Card Invoices'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'ordering': ['due_date', 'payment_type'], 'verbose_name': 'Payment Status', 'verbose_name_plural': 'Payment Statuses'},
        ),
    ]
