# Generated by Django 5.2.4 on 2026-07-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_creditcardinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'ordering': ['due_date'], 'verbose_name': 'Payment Status', 'verbose_name_plural': 'Payment Statuses'},
        ),
        migrations.AlterUniqueTogether(
            name='paymentstatus',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='month_year',
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='payment_type',
        ),
    ]
